# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

url: https://www.blackradley.com

# Permalinks
permalink:        pretty

# Social
title: Black Radley 
description: The Enterprise People

gems:
   - jekyll-paginate
   - jekyll-sitemap
